// DO NOT EDIT. ops/registry/apps.yml에서 생성된 홈페이지 앱 메타데이터다.
export const generatedAppMeta = [
  {
    "id": "outbom",
    "name": "야외봄",
    "englishName": "OutBom",
    "repo": "robom-labs/outbom",
    "version": "0.27.0",
    "dataVersion": "runtime-weather-v1",
    "webUrl": "https://robom-labs.github.io/outbom/",
    "healthcheckUrl": "https://robom-labs.github.io/outbom/",
    "deployProvider": "github-pages",
    "basePath": "/outbom/",
    "privacyUrl": "https://robom.kr/privacy/outbom",
    "supportUrl": "https://robom.kr/support",
    "androidAppId": "kr.robom.outbom",
    "iosBundleId": "kr.robom.outbom",
    "googlePlayUrl": "https://play.google.com/store/apps/details?id=kr.robom.outbom",
    "googlePlayStatus": "live",
    "appStoreUrl": "",
    "appStoreStatus": "planned",
    "pwaInstallUrl": "https://robom-labs.github.io/outbom/",
    "stableInstallUrl": "https://robom.kr/get/outbom",
    "mobileStatus": "native-production-live",
    "familySpecVersion": "1.1.0",
    "lastVerifiedAt": "2026-08-10T20:43:39+09:00",
    "lastDeployedSha": "6854a300006381b066c6de9eda7ebdf962f85d1d",
    "lastDataSyncAt": "2026-07-16T13:42:23+09:00",
    "freshnessStatus": "runtime"
  },
  {
    "id": "homebom",
    "name": "청약봄",
    "englishName": "HomeBom",
    "repo": "robom-labs/homebom",
    "version": "0.17.1",
    "dataVersion": "official-notices-runtime-v1",
    "webUrl": "https://robom-labs.github.io/homebom/",
    "healthcheckUrl": "https://robom-labs.github.io/homebom/",
    "deployProvider": "github-pages",
    "basePath": "/homebom/",
    "privacyUrl": "https://robom.kr/privacy/homebom",
    "supportUrl": "https://robom.kr/support",
    "androidAppId": "kr.robom.homebom",
    "iosBundleId": "kr.robom.homebom",
    "googlePlayUrl": "",
    "googlePlayStatus": "internal",
    "appStoreUrl": "",
    "appStoreStatus": "planned",
    "pwaInstallUrl": "https://robom-labs.github.io/homebom/",
    "stableInstallUrl": "https://robom.kr/get/homebom",
    "mobileStatus": "native-closed-test-review",
    "familySpecVersion": "1.1.0",
    "lastVerifiedAt": "2026-08-08T22:34:00+09:00",
    "lastDeployedSha": "04884ce4ed3d11bdc05b579a383eadbf8d5eff85",
    "lastDataSyncAt": "2026-08-08T21:05:02+09:00",
    "freshnessStatus": "runtime"
  },
  {
    "id": "runningbom",
    "name": "러닝봄",
    "englishName": "RunningBom",
    "repo": "robom-labs/runningbom",
    "version": "0.21.0",
    "dataVersion": "2026.08.08-race-data-34",
    "webUrl": "https://robom-labs.github.io/runningbom/",
    "healthcheckUrl": "https://robom-labs.github.io/runningbom/",
    "deployProvider": "github-pages",
    "basePath": "/runningbom/",
    "privacyUrl": "https://robom.kr/privacy/runningbom",
    "supportUrl": "https://robom.kr/support",
    "androidAppId": "kr.robom.runningbom",
    "iosBundleId": "kr.robom.runningbom",
    "googlePlayUrl": "",
    "googlePlayStatus": "internal",
    "appStoreUrl": "",
    "appStoreStatus": "planned",
    "pwaInstallUrl": "https://robom-labs.github.io/runningbom/",
    "stableInstallUrl": "https://robom.kr/get/runningbom",
    "mobileStatus": "native-closed-test-active",
    "familySpecVersion": "1.1.0",
    "lastVerifiedAt": "2026-08-08T22:54:00+09:00",
    "lastDeployedSha": "9aac3826fba02a53c7d5b08b318ae5cc288cb2ca",
    "lastDataSyncAt": "2026-08-08T04:18:56+09:00",
    "freshnessStatus": "healthy"
  },
  {
    "id": "certbom",
    "name": "자격증봄",
    "englishName": "CertBom",
    "repo": "robom-labs/certbom",
    "version": "0.9.0",
    "dataVersion": "2026.07.24-v4",
    "webUrl": "https://certbom.vercel.app/",
    "healthcheckUrl": "https://certbom.vercel.app/",
    "deployProvider": "vercel",
    "basePath": "/",
    "privacyUrl": "https://robom.kr/privacy/certbom",
    "supportUrl": "https://robom.kr/support",
    "androidAppId": "kr.robom.certbom",
    "iosBundleId": "kr.robom.certbom",
    "googlePlayUrl": "https://play.google.com/store/apps/details?id=kr.robom.certbom",
    "googlePlayStatus": "live",
    "appStoreUrl": "",
    "appStoreStatus": "planned",
    "pwaInstallUrl": "https://certbom.vercel.app/",
    "stableInstallUrl": "https://robom.kr/get/certbom",
    "mobileStatus": "native-production-live",
    "familySpecVersion": "1.1.0",
    "lastVerifiedAt": "2026-08-09T20:45:48+09:00",
    "lastDeployedSha": "a8ec73a89ab9acece4738fa6b9148d16b6bb3fee",
    "lastDataSyncAt": "2026-07-24T14:30:00+09:00",
    "freshnessStatus": "last-known-good"
  }
] as const;
